"""Fix field types + add default vals

Revision ID: 87a58bf99609
Revises: f7b8c7ce818f
Create Date: 2022-05-26 11:27:19.959137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a58bf99609'
down_revision = 'f7b8c7ce818f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('author_list', sa.PickleType(), nullable=True))
    op.add_column('package', sa.Column('subscriptions', sa.PickleType(), nullable=True))
    op.drop_constraint('package_author_fkey', 'package', type_='foreignkey')
    op.drop_column('package', 'author')
    op.add_column('user', sa.Column('authored_packages', sa.PickleType(), nullable=True))
    op.drop_constraint('user_subscribed_packages_fkey', 'user', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_subscribed_packages_fkey', 'user', 'package', ['subscribed_packages'], ['id'])
    op.drop_column('user', 'authored_packages')
    op.add_column('package', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('package_author_fkey', 'package', 'user', ['author'], ['id'])
    op.drop_column('package', 'subscriptions')
    op.drop_column('package', 'author_list')
    # ### end Alembic commands ###
