"""FIX FIELDS PLEASEEEE

Revision ID: f8c1a77295af
Revises: 87a58bf99609
Create Date: 2022-05-26 13:44:24.493675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c1a77295af'
down_revision = '87a58bf99609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
